pipeline:

  deploy:
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    host: nansen.online.ntnu.no
    port: 22
    username: root
    key: ${SSH_KEY}
    command_timeout: 600s
    when:
      event: push
      branch: master
    script:
      - /srv/www/smashrank/deploy.sh
